### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by PSYCHO1512** [ElectroGamesYT/BetterHomes#2]
when you dont have a home set and do teleport to home it crashed the server

**Comment by YT-Duckyyy** [comment]
[15:05:43.542] [Server thread/CRITICAL]: InvalidArgumentException: "No option at index 0, cannot set as default" (EXCEPTION) in "plugins/BetterHomes (1).phar/src/Electro/BetterHomes/libs/dktapps/pmforms/element/BaseSelector" at line 47
--- Stack trace ---
  #0 plugins/BetterHomes (1).phar/src/Electro/BetterHomes/BetterHomes(161): Electro\BetterHomes\libs\dktapps\pmforms\element\BaseSelector->__construct(string[5] homes, string[28] Select A Home To Teleport To, array[0])
  #1 plugins/BetterHomes (1).phar/src/Electro/BetterHomes/BetterHomes(98): Electro\BetterHomes\BetterHomes->homeTeleportForm(object ipad54\netherblocks\player\Player#413653)
  #2 plugins/BetterHomes (1).phar/src/Electro/BetterHomes/libs/dktapps/pmforms/MenuForm(90): Electro\BetterHomes\BetterHomes->Electro\BetterHomes\{closure}(object ipad54\netherblocks\player\Player#413653, int 0)
  #3 pmsrc/src/player/Player(2011): Electro\BetterHomes\libs\dktapps\pmforms\MenuForm->handleResponse(object ipad54\netherblocks\player\Player#413653, int 0)
  #4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(897): pocketmine\player\Player->onFormSubmit(int 1, int 0)
  #5 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#455732)
  #6 pmsrc/src/network/mcpe/NetworkSession(392): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#444974)
  #7 pmsrc/src/network/mcpe/NetworkSession(355): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#455732, string[7] e...0..)
  #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[10] cOedd2.b..)
  #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[19] .^j.m..0.!;.9L....v)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#411971)
  #11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #13 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1662822343.5829)
  #14 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #15 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #16 pmsrc/src/PocketMine(328): pocketmine\server()
  #17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by ElectroGamesYT** [comment]
This has been fixed, thank you.
